## Core Foundations of Pandas -(PHASE-1)

#### The primary Data structure
1. pd.series
2. pd.dataframe

In [2]:
import pandas as pd
import numpy as np

In [ ]:
# cresting series
ages = pd.Series([22,25,30],name="age")

# creating dataframe
data ={
    "Name":  ["Alice","Bob","Charlie","David"],
    "Age":   [25,30,np.nan,22],
    "Dept" : ["Hr","It","It","Hr"],
    "Salary":[50000,62000,70000,48000],
}
df =pd.DataFrame(data)

# ages
df

      Name   Age Dept  Salary
0    Alice  25.0   Hr   50000
1      Bob  30.0   It   62000
2  Charlie   NaN   It   70000
3    David  22.0   Hr   48000

In [30]:
print(df.head(1))
print(df.shape)
print(df.info)
print(df.dtypes)

    Name   Age Dept  Salary
0  Alice  25.0   Hr   50000
(4, 4)
<bound method DataFrame.info of       Name   Age Dept  Salary
0    Alice  25.0   Hr   50000
1      Bob  30.0   It   62000
2  Charlie   NaN   It   70000
3    David  22.0   Hr   48000>
Name          str
Age       float64
Dept          str
Salary      int64
dtype: object

In [31]:
print(df)
print(df.describe())

      Name   Age Dept  Salary
0    Alice  25.0   Hr   50000
1      Bob  30.0   It   62000
2  Charlie   NaN   It   70000
3    David  22.0   Hr   48000
             Age        Salary
count   3.000000      4.000000
mean   25.666667  57500.000000
std     4.041452  10376.254944
min    22.000000  48000.000000
25%    23.500000  49500.000000
50%    25.000000  56000.000000
75%    27.500000  64000.000000
max    30.000000  70000.000000

In [40]:
print(df)


df.loc[0:2,["Name","Salary"]]
df.iloc[0:2,0:2]
df.at[0,"Name"]
df.iat[0,1]

      Name   Age Dept  Salary
0    Alice  25.0   Hr   50000
1      Bob  30.0   It   62000
2  Charlie   NaN   It   70000
3    David  22.0   Hr   48000

np.float64(25.0)

#### Boolean Filtering & Logical Operators

In [49]:
# it high earners above 60k
it_high_earner = (df["Dept"]=="It") & (df["Salary"] >= 60000)
df[it_high_earner]

# filter:  not in hr 
not_hr = ~(df["Dept"] =="Hr")
# not_hr =  (df["Dept"] !="Hr")
df[not_hr]

      Name   Age Dept  Salary
1      Bob  30.0   It   62000
2  Charlie   NaN   It   70000

In [10]:
df["Dept"].nunique()
df["Dept"].value_counts()
df.isnull().sum()
df.isna().sum()

Name      0
Age       1
Dept      0
Salary    0
dtype: int64

In [22]:
# handling
# df.fillna({"Age":df["Age"].median()})
print(df)
df["Age"].ffill()
df["Age"].bfill()

      Name   Age Dept  Salary
0    Alice  25.0   Hr   50000
1      Bob  30.0   It   62000
2  Charlie   NaN   It   70000
3    David  22.0   Hr   48000

0    25.0
1    30.0
2    22.0
3    22.0
Name: Age, dtype: float64

In [ ]:
df.drop_duplicates()

      Name   Age Dept  Salary
0    Alice  25.0   Hr   50000
1      Bob  30.0   It   62000
2  Charlie   NaN   It   70000
3    David  22.0   Hr   48000

In [35]:
data_2 ={
    "Name":  ["Alice","Bob","Charlie","David","Alice","Alice","Charlie"],
    "Age":   [25,30,np.nan,22,25,25,np.nan],
    "Dept" : ["Hr","It","It","Hr","Hr","Hr","It"],
    "Salary":[50000,62000,70000,48000,50000,50000,70000],
}
df_2 =pd.DataFrame(data_2)

In [ ]:
# print(df_2[~df_2.duplicated()])
# df_2.drop_duplicates(subset=["Name"],keep="last")
print(df_2["Dept"].unique())
print(df_2["Dept"].nunique())
print(df_2["Dept"].value_counts())
df_2.describe()

<StringArray>
['Hr', 'It']
Length: 2, dtype: str
2
Dept
Hr    4
It    3
Name: count, dtype: int64

             Age        Salary
count   5.000000      7.000000
mean   25.400000  57142.857143
std     2.880972   9923.517042
min    22.000000  48000.000000
25%    25.000000  50000.000000
50%    25.000000  50000.000000
75%    25.000000  66000.000000
max    30.000000  70000.000000