# PANDAS BY: Intelipath

## series - first 1D data structure

## Random functions

In [45]:
import pandas as pd

In [46]:
series = pd.Series([1,2,3,4,5,6,7,8])
print(series)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [47]:
print(series.dtype)

int64

In [48]:
print(series.values)

[1 2 3 4 5 6 7 8]

In [49]:
print(series.index)

RangeIndex(start=0, stop=8, step=1)

In [50]:
series.name="ran_numbers"
print(series.name)

ran_numbers

In [51]:
print(series)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
Name: ran_numbers, dtype: int64

## indexing

In [52]:
print(f"0th number: {series[0]}")
print(f"0 to 8 number: {series[0:9]}")

0th number: 1
0 to 8 number: 0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
Name: ran_numbers, dtype: int64

### iloc indexing

In [53]:
print(series.iloc[[0,1,2,3]])

0    1
1    2
2    3
3    4
Name: ran_numbers, dtype: int64

## index changing

In [54]:
index = ["first","second","third","forth","fifth","sixth","seventh","eight"]
series.index = index
print(series)

first      1
second     2
third      3
forth      4
fifth      5
sixth      6
seventh    7
eight      8
Name: ran_numbers, dtype: int64

In [55]:
print(series["first"])
# print(series.iloc["first"]) this will not work
print(series.iloc[0])

1
1

## labeled basedd indexing

In [56]:
# loc ->  labeled based indexing
print(series.loc["first"])

# in this function start as well as stop value also included
print(series.loc["first":"eight"])

1
first      1
second     2
third      3
forth      4
fifth      5
sixth      6
seventh    7
eight      8
Name: ran_numbers, dtype: int64

## creating series using dictionary

In [57]:
student = {
    "name": "Shivam",
    "age": 20,
    "course": "BSc Computer Science",
    "city": "Greater Noida",
    "marks": 89,
    "passed": True
}

In [58]:
s2=pd.Series(student,name="knight_rdr")
print(s2)

name                    Shivam
age                         20
course    BSc Computer Science
city             Greater Noida
marks                       89
passed                    True
Name: knight_rdr, dtype: object

## Conditional selection

In [59]:
fruits_protein= {
    "Guava": 2.6,
    "Avocado": 2.0,
    "Jackfruit": 1.7,
    "Blackberries": 1.4,
    "Kiwi": 1.1,
    "Orange": 0.9,
    "Pomegranate": 1.7,
    "Banana": 1.1,
    "Apple": 0.3,
    "Mango": 0.8,
    "Papaya": 0.5,
    "Pineapple": 0.5,
    "Watermelon": 0.6,
    "Grapes": 0.7,
    "Pear": 0.4,
    "Peach": 0.9,
    "Strawberry": 0.8,
    "Blueberry": 0.7,
    "Cherry": 1.1,
    "Coconut": 3.3
}

In [60]:
fruit = pd.Series(fruits_protein,name="Protein rate")
print(fruit>2) # tis well give the Boolean series 
f2 = fruit>2
print(fruit[f2])

Guava            True
Avocado         False
Jackfruit       False
Blackberries    False
Kiwi            False
Orange          False
Pomegranate     False
Banana          False
Apple           False
Mango           False
Papaya          False
Pineapple       False
Watermelon      False
Grapes          False
Pear            False
Peach           False
Strawberry      False
Blueberry       False
Cherry          False
Coconut          True
Name: Protein rate, dtype: bool
Guava      2.6
Coconut    3.3
Name: Protein rate, dtype: float64

## logical operators:
and &
or ||
not ~

In [61]:
print(fruit[(fruit>0.5) & (fruit<1)])

fruit["Mango"] = 2 # nodifying an particular index's value
print(fruit)

Orange        0.9
Mango         0.8
Watermelon    0.6
Grapes        0.7
Peach         0.9
Strawberry    0.8
Blueberry     0.7
Name: Protein rate, dtype: float64
Guava           2.6
Avocado         2.0
Jackfruit       1.7
Blackberries    1.4
Kiwi            1.1
Orange          0.9
Pomegranate     1.7
Banana          1.1
Apple           0.3
Mango           2.0
Papaya          0.5
Pineapple       0.5
Watermelon      0.6
Grapes          0.7
Pear            0.4
Peach           0.9
Strawberry      0.8
Blueberry       0.7
Cherry          1.1
Coconut         3.3
Name: Protein rate, dtype: float64

## Data Frame - second 2D data structure

In [62]:
import numpy as np

In [63]:
ser= pd.Series(['a',np.nan,1,np.nan,2])
series.notnull().sum()

np.int64(8)

In [64]:
data = {
    "Name" : ["Alice","Bob","Charlie","David","Eve","Alice"],
    "Age"  : [25,30,35,np.nan,29,25],
    "Department" : ["HR","IT","Finance","IT","HR","HR"],
    "Salary"   : [50000,60000,70000,62000,np.nan,50000]
}

In [65]:
df = pd.DataFrame(data) 
print(df.head(2),"\n",df.tail(2))

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0
     Name   Age Department   Salary
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [66]:
## loc and iloc functios
print(df.iloc[1:3])
# print(df.loc[0:3, [ "Age","Departmen t"]])

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0

In [67]:
print(df.drop("Age",axis=1))
# this will remove entire column from the data ,
#  and we have to use axis attribute compulsary
#  NOTE: this will return new datafdrame 
# if we want to change the original dataframe ,
# we use inplace attribute inplace = "True" , default it is false

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [68]:
print(df.shape) 
print(f"using info function:-------------- \n{df.info()}")  
# this info and dtype function have different use

(6, 4)
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Age         5 non-null      float64
 2   Department  6 non-null      str
 3   Salary      5 non-null      float64
dtypes: float64(2), str(2)
memory usage: 324.0 bytes
using info function:--------------
None

In [69]:
print(f"using dtype function:-------------- \n{df.dtypes}")

using dtype function:--------------
Name              str
Age           float64
Department        str
Salary        float64
dtype: object

In [70]:
print(f"using describe function:-------------- \n{df.describe()}") 
print(f"using describe attribute:-------------- \n{df.describe}")

using describe function:--------------
             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000
using describe attribute:--------------
<bound method NDFrame.describe of       Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0>

### broadcasting in pandas

In [71]:
df["Salary"] = df["Salary"] + 5000

### renaming the columns

In [72]:
df.rename(columns={"Department": "dept"},inplace=True)
df

      Name   Age     dept   Salary
0    Alice  25.0       HR  55000.0
1      Bob  30.0       IT  65000.0
2  Charlie  35.0  Finance  75000.0
3    David   NaN       IT  67000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  55000.0

In [73]:
#  for unique values
df["dept"].unique()

<StringArray>
['HR', 'IT', 'Finance']
Length: 3, dtype: str

In [74]:
df["dept"].value_counts()

dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [75]:
df["promoted salary"] = df["Salary"] *10
df

      Name   Age     dept   Salary  promoted salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

### data cleaning

In [76]:
df.isnull().sum()

Name               0
Age                1
dept               0
Salary             1
promoted salary    1
dtype: int64

In [77]:
df.dropna(how = "any")# if any values in that particular row is null,
#then drop that row otherwise NO.

      Name   Age     dept   Salary  promoted salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
5    Alice  25.0       HR  55000.0         550000.0

In [78]:
df.dropna(how ="all") # if all values in that particular row are null,
#then drop that row otherwise NO.

      Name   Age     dept   Salary  promoted salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0

In [79]:
# filling null value with particular or most repeated valued
# df.fillna(0) # filling with particular value

# this is suggested but it would not make change in original dataframe
# df["Age"].fillna(df["Age"].mean(),inplace=True) 

# we use this for changing the value in original dataset
# df.fillna({"Age":df["Age"].mean()},inplace=True)
# df.fillna({"Salary": df["Salary"].median()},inplace=True)

In [80]:
#original dataset
print(df)
# forward fill and backword fill
print(df["Age"].ffill())
# backward fill and backword fill
print(df["Salary"].bfill())

      Name   Age     dept   Salary  promoted salary
0    Alice  25.0       HR  55000.0         550000.0
1      Bob  30.0       IT  65000.0         650000.0
2  Charlie  35.0  Finance  75000.0         750000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  55000.0         550000.0
0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64
0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    55000.0
5    55000.0
Name: Salary, dtype: float64

In [81]:
df["Name"]= df["Name"].replace("Charlie","shivam")
df

     Name   Age     dept   Salary  promoted salary
0   Alice  25.0       HR  55000.0         550000.0
1     Bob  30.0       IT  65000.0         650000.0
2  shivam  35.0  Finance  75000.0         750000.0
3   David   NaN       IT  67000.0         670000.0
4     Eve  29.0       HR      NaN              NaN
5   Alice  25.0       HR  55000.0         550000.0

#### dealing with suplicate data

In [82]:
# df_dup = df[df.duplicated(keep="last")]
# df_dup = df[df.duplicated(keep="first")]
# df_dup

In [83]:
df = df.drop_duplicates()
df

     Name   Age     dept   Salary  promoted salary
0   Alice  25.0       HR  55000.0         550000.0
1     Bob  30.0       IT  65000.0         650000.0
2  shivam  35.0  Finance  75000.0         750000.0
3   David   NaN       IT  67000.0         670000.0
4     Eve  29.0       HR      NaN              NaN

#### looking with invalid values

In [84]:
df["promoted salary"] = df["promoted salary"].apply(lambda x: x/10 if x>650000 else x)
df

     Name   Age     dept   Salary  promoted salary
0   Alice  25.0       HR  55000.0         550000.0
1     Bob  30.0       IT  65000.0         650000.0
2  shivam  35.0  Finance  75000.0          75000.0
3   David   NaN       IT  67000.0          67000.0
4     Eve  29.0       HR      NaN              NaN

#### strings

In [85]:
# Name = "alice_fernandas"
# df[["First_name","Last_name"]] = df["name"].str.strip("_")

## moreover lamdas and nor,mal function

In [86]:
def multi_age(x):
    return x*2 
# without using lambda function 
df["Age"] =df["Age"].apply(multi_age)
df

     Name   Age     dept   Salary  promoted salary
0   Alice  50.0       HR  55000.0         550000.0
1     Bob  60.0       IT  65000.0         650000.0
2  shivam  70.0  Finance  75000.0          75000.0
3   David   NaN       IT  67000.0          67000.0
4     Eve  58.0       HR      NaN              NaN

In [87]:
# with uding lambda function
df["Age"] = df["Age"].apply( lambda x: x/2)
df

     Name   Age     dept   Salary  promoted salary
0   Alice  25.0       HR  55000.0         550000.0
1     Bob  30.0       IT  65000.0         650000.0
2  shivam  35.0  Finance  75000.0          75000.0
3   David   NaN       IT  67000.0          67000.0
4     Eve  29.0       HR      NaN              NaN

## joins and merges
joins:- left,right,outer and inner
merges:- concat, merge